# OpenWrt metapackage for PTP nodes
# Copyright 2012 Personal Telco Project


include $(TOPDIR)/rules.mk

PKG_NAME:=ptp
PKG_VERSION:=0.1
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/ptp
  SECTION:=personaltelco
  CATEGORY:=Personal Telco
  DEPENDS:=batman-adv
  TITLE:=Personal Telco Project node metapackage
endef

